Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/aws_cdk"
  config.vm.synced_folder "#{Dir.home}/.aws", "/root/.aws"
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    # d.vagrant_vagrantfile = "../Vagrantfile"
    # d.force_host_vm = true
  end
end
